# Some commonly used options have been documented as comments in this file.
# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-14.7

packages:
- backend

extra-deps:
  - git: https://github.com/dnsco/twilio-haskell
    commit: 31b3198c80c3708985e54baf4ac99c3077ed3b64

# Override default flag values for local packages and extra-deps
# flags: {}

# Allow a newer minor version of GHC than the snapshot specifies
compiler-check: newer-minor
