# Some commonly used options have been documented as comments in this file.
# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-14.7

packages:
- api

extra-deps:
  - git: https://github.com/smaccoun/servant-ts
    commit: e615995e1e83e49e155aa996f93627a78084f4e9
    subdirs:
      - lib
  - git: https://github.com/smaccoun/aeson-generic-ts
    commit: 080ec883e77aad45cc01cc211bdb9998bd47e66e

# Override default flag values for local packages and extra-deps
# flags: {}

# Allow a newer minor version of GHC than the snapshot specifies
compiler-check: newer-minor
