version: 2.1
orbs:
  heroku: circleci/heroku@0.0.8
jobs:
  build-api:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          name: Restore Cached Dependencies
          keys:
            - coach-v1-{{ checksum "stack.yaml" }}-{{ checksum "api/package.yaml" }}
            - coach-v1-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: pushd api; stack --no-terminal setup; popd;
      - run:
          name: Run tests
          command: pushd api; stack --no-terminal test; popd;
      - run:
          name: Install executable
          command: pushd api; stack --no-terminal install; popd;
      - save_cache:
          name: Cache Dependencies
          key: coach-v1-{{ checksum "stack.yaml" }}-{{ checksum "api/package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
  #      - store_artifacts:
  #          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
  #          path: ~/.local/bin/circleci-demo-haskell-exe
  #          destination: circleci-demo-haskell-exe
  build-frontend:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
#      - restore_cache:
#        name: Restore Yarn Package Cache
#        key: yarn-packages-{{ checksum "fontend/yarn.lock" }}
      - run:
          name: Install Dependencies
          command: cd frontend; yarn install --frozen-lockfile
      - run:
          name: Typecheck and Test
          command: cd frontend; yarn test:ci
#      - save_cache:
#          name: Save Yarn Package Cache
#          key: yarn-packages-{{ checksum "frontend/yarn.lock" }}
#          paths:
#            - ~/.cache/yarn
  deploy-api:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master
          app-name: bitchdidyou-api
  deploy-frontend:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master
          app-name: bitchdidyou-frontend
workflows:
  version: 2
  build-deploy-api-and-frontend:
    jobs:
      - build-api
      - build-frontend
      - deploy-api:
          requires:
            - build-api
            - build-frontend
          filters:
            branches:
              only: master
      - deploy-frontend:
          requires:
            - build-api
            - build-frontend
          filters:
            branches:
              only: master